export const funFactsData = [
    "Moore's Law: The number of transistors on a microchip doubles about every two years, a trend that has driven the IT revolution.",
    "From Sand to Silicon: The primary material for microchips is silicon, which is purified from common sand (silicon dioxide).",
    "The First 'Bug': The term 'computer bug' was popularized after a real moth was found trapped in a relay of the Harvard Mark II computer in 1947.",
    "Ultra-Clean Rooms: Chip fabrication plants (fabs) have cleanrooms that are thousands of times cleaner than a hospital operating room to prevent dust from ruining the microscopic circuits.",
    "Nanometer Scale: The smallest transistors in modern chips are measured in nanometers, making them smaller than a single virus.",
    "AI Training Energy: Training a large AI model like GPT-3 can consume as much energy as it takes to power several households for a year.",
    "The Kilby Tan: Jack Kilby, the inventor of the integrated circuit, didn't have a piece of silicon to build his first prototype, so he used a sliver of germanium.",
    "The Sound of a Transistor: The first transistor, invented at Bell Labs in 1947, was a point-contact transistor that looked like a small, three-legged stool. When it worked, it made a faint 'psst' sound.",
    "The Zettabyte Era: The amount of data generated by the world is now measured in zettabytes. One zettabyte is equivalent to about 250 billion DVDs.",
    "The Speed of Light: The speed of light is a fundamental limit in chip design. As chips get faster, the time it takes for signals to travel across the chip becomes a major bottleneck.",
    "The Cost of a Fab: A state-of-the-art semiconductor fabrication plant can cost over $10 billion to build.",
    "The First Microprocessor: The first commercially available microprocessor was the Intel 4004, released in 1971. It contained 2,300 transistors and was originally designed for a calculator."
];
